name: 'Stuck Pull Request Notifier'
branding:
  color: 'yellow'
  icon: 'alert-triangle'
description: 'Automatically label and mention/notify users about stuck pull requests.'
runs:
  main: 'dist/index.js'
  using: 'node12'
