name: 'Stuck Pull Request Notifier'

description: 'Automatically label and mention/notify users about stuck pull requests.'

branding:
  color: 'yellow'
  icon: 'alert-triangle'

inputs:
  repo-token:
    description: Usually a GITHUB_TOKEN with enough permissions to comment on PRs
    required: true
  message:
    description: The text of the comment on the PRs which got stuck; you can mention users/teams; at least one user should be mentioned here or be provided in `assigneeIds`
    required: true
  search-query:
    description: Search query to filter the open PRs; example `author:app/dependabot` for dependabot PRs
    required: true
  cutoff:
    description: Period after which a PR is considered stuck; defaults to 24h
    required: false
    default: 24h
  label:
    description: What label to apply to the stuck PRs; LABEL NEEDS TO EXIST; defaults to `stuck`
    required: false
    default: stuck
  assigneeIds:
    description: Which additional user(s) or team(s) to assign the PRs to, space separated; example '@user1 @user 2'; at least one user should be listed here or be provided as mention in `message`
    required: false
    default: ''

runs:
  main: 'dist/index.js'
  using: 'node16'
